
pipelines:
  default:
    - step:
        name: 'Build NPM'
        image: node:lts
        script:
          - npm i mediasoup
          - npm i
        caches:
          - nodemodules
        artifacts:
          - node_modules/**
    - step:
        name: 'Docker build'
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli

          - aws configure set aws_access_key_id "${AWS_KEY}"
          - aws configure set aws_secret_access_key "${AWS_SECRET}"
          - eval $(aws ecr get-login --no-include-email --region eu-west-2 | sed 's;https://;;g')

          - cp deploy/Dockerfile.bitbucket-pipeline .
          - docker build -t kidsloop-sfu -f Dockerfile.bitbucket-pipeline .
          - docker tag kidsloop-sfu:latest 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu:latest
          - docker tag kidsloop-sfu:latest 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu:latest-$BITBUCKET_BUILD_NUMBER
          - docker push 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu:latest
          - docker push 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu:latest-$BITBUCKET_BUILD_NUMBER
        services:
          - docker


definitions:
  caches:
    nodemodules: ./node_modules