
name: Bump version

concurrency:
    group: BumpVersion
    cancel-in-progress: true

on:
    workflow_dispatch:
        inputs:
            prerelease:
                description: Prerelease tag (optional)
                required: false
                type: string
                default: ''

jobs:
    confirm-version-generation:
        runs-on: ubuntu-latest
        environment: latest
        steps:
            - name: Debug message
              run: echo Version generation confirmed

    install:
        needs: [confirm-version-generation]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@d4a107eea49a9e8f2b0e411b59884723301c3213
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    test:
        needs: [install]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-test-jest.yml@d4a107eea49a9e8f2b0e411b59884723301c3213

    generate-version:
        needs: [test]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-generate-version.yml@d4a107eea49a9e8f2b0e411b59884723301c3213
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    build-and-push:
        needs: [generate-version]
        runs-on: ubuntu-latest
        steps:
            - uses: KL-Engineering/github-action-workflows/.github/actions/npm-ci@d4a107eea49a9e8f2b0e411b59884723301c3213
              with:
                NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
            - name: NPM Build
              id: npm-build
              run: npm run build
            - name: Build and Push Container
              uses: KL-Engineering/github-action-workflows/.github/actions/docker-build-push@d4a107eea49a9e8f2b0e411b59884723301c3213
              with:
                environment: ${{ needs.generate-version.outputs.tag }}
                region: global
                ecr_repository: kidsloop-sfu
                dockerfile_dir: deploy
                dockerfile_name: Dockerfile.ci-pipeline
                dockerfile_context: .
                ecr_aws_region: eu-west-2
                ecr_registry: 942095822719.dkr.ecr.eu-west-2.amazonaws.com
                ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
                ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
