name: Create release candidate
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Prerelease tag (optional)
        required: false
        type: string
        default: ''
      release_as:
        required: true
        type: choice
        default: auto
        description: If you want an automated or a manual version bump
        options:
          - auto
          - major
          - minor
          - patch

      ecs_aws_service:
        required: true
        type: string
        default: kidsloop-sfu
        description: ECS target cluster
      aws_account_id:
        required: false
        type: string
        default: "871601235178"
        description: AWS account
      ecs_aws_cluster:
        required: false
        type: string
        default: kidsloop-alpha
        description: ECS cluster
      ecs_aws_region:
        required: false
        type: string
        default: ap-northeast-2
        description: default AWS region
    secrets:
      AWS_ACCESS_KEY_ID_ALPHA_DEV:
        required: true
      AWS_SECRET_ACCESS_KEY_ALPHA_DEV:
        required: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump-version:
    uses: KL-Engineering/github-action-workflows/.github/workflows/bump-version.yml@v3.1.0
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    with:
      prerelease: ${{ github.event.inputs.prerelease }}
      release_as: ${{ github.event.inputs.release_as }}

  dockerise:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      # Fetch project source
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: true
      - run: |
          export VERSION_TAG=$(git describe --tags --abbrev=0)
          echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - uses: KL-Engineering/github-action-workflows/.github/workflows/docker-build-push.yml@v3.0.1
        with:
          environment: ${{ needs.get-latest-tag.outputs.tag }}
          region: eu-west-2
          ecr_repository: kidsloop-sfu
          dockerfile_dir: deploy
          dockerfile_name: Dockerfile.ci-pipeline
          ecr_aws_region: eu-west-2
          ecr_registry: 942095822719.dkr.ecr.eu-west-2.amazonaws.com