name: Deploy to Alpha (job)

on:
  workflow_call:
    inputs:
      ecs_aws_service:
        required: true
        type: string
        default: kidsloop-alpha-live-sfu
      aws_account_id:
        required: false
        type: string
        default: 871601235178
      ecs_aws_cluster:
        required: false
        type: string
        default: kidsloop-alpha
      ecs_aws_region:
        required: false
        type: string
        default: ap-northeast-2
    secrets:
      AWS_ACCESS_KEY_ID_ALPHA_DEV:
        required: true
      AWS_SECRET_ACCESS_KEY_ALPHA_DEV:
        required: true

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ALPHA_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALPHA_DEV }}
          aws-region: ${{ inputs.ecs_aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update service
        env:
          ACCOUNT_ID: ${{ inputs.aws_account_id }}
          ECS_SERVICE: ${{ inputs.ecs_aws_service }}
          ECS_CLUSTER: ${{ inputs.ecs_aws_cluster }}
          ECS_REGION: ${{ inputs.ecs_aws_region }}
        run: |
          aws ecs update-service \
            --region $ECS_REGION \
            --cluster $ECS_CLUSTER \
            --force-new-deployment \
            --service arn:aws:ecs:$ECS_REGION:$ACCOUNT_ID:service/$ECS_CLUSTER/$ECS_SERVICE
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE
          export AWS_ECS_IMAGE=$(aws ecs describe-task-definition \
            --region $ECS_REGION \
            --task-definition $ECS_SERVICE./ \
            --query "taskDefinition.containerDefinitions[*] | [?name=='$ECS_SERVICE'].image" \
            --output text)
          echo "deployed => $AWS_ECS_IMAGE"
          export OCI_TAG=$(echo $AWS_ECS_IMAGE | awk -F ':' '{ print $NF }')
          echo "Oci tag => $OCI_TAG"
          echo ::set-output name=ocitag::$OCI_TAG
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} when deploying ${{ inputs.ecs_aws_cluster }}:${{ inputs.ecs_aws_service }}:${{ steps.deploy.outputs.ocitag }}'
          footer: '${{ inputs.aws_account_id }}:${{ inputs.ecs_aws_region }}'
          notify_when: 'failure'
          mention_users: 'U0160UUNH8S,U0080UUAA9N'
          mention_users_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}