name: Pull requests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  conventional-pr-title:
    uses: KL-Engineering/github-action-workflows/.github/workflows/conventional-pr-title.yml@v3.0.1

  tests:
    uses: KL-Engineering/kidsloop-sfu/.github/workflows/tests.yml@bb6cacc0cd1ad243b9c9bbf69b779f778af329b6
